[build-system]
requires = ["setuptools>=39.2.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
python_files =["test_*.py", "bench_*.py"]
python_functions = ["test_*", "bench_*"]
