name: publish-package

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish to TestPyPI and PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Get repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements/build.txt
      - name: Build Project
        run: |
          ./script-run build
      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/  
      - name: Publish to PyPI
        # The above should have succeeded. If it didn't, this won't run.
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
