name: run-tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'

jobs:
  lint:
    name: PyLint linting
    runs-on: ubuntu-latest

    steps:
      - name: Get repo.
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install python@latest
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pylint
      - name: Lint code
        run: |
          python -m pylint ./python_http_parser
          python -m pylint ./tests

  test:
    if: always()
    name: PyTest testing
    runs-on: ubuntu-latest
    needs: lint
    # We'll need to do some matrix stuff with this.
    strategy:
      matrix:
        # Only test on Python 3.5+ for now.
        python-version: [
          3.5,
          3.6,
          3.7,
          3.8,
          3.9
        ]

    steps:
      - name: Get repo.
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install python@${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
      - name: Run tests
        run: python -m pytest
